### ISSUE TITLE
Unable to downgrade version even with update option set to true

### ISSUE THREAD

**Issue by dshrestha** [rse/grunt-bower-install-simple#14]
I wanted to downgrade the jquery version after I had already deployed it but I am not able to do so. My bower.json looked like this:

<code>
"dependencies": {
    "jquery": ">=1.11.2"
}
</code>

which caused it to fetch the ver 2.0 of jquery but after realizing my problem I changed it to:
<code>
"dependencies": {
    "jquery": "~1.11.2"
}
</code>

and in my gruntfile.js I have bower set up like this:

<code>
"bower-install-simple": {
            options: {
                update: true
            },
            dist: {
                options: {
                    production: true
                }
            },
            dev: {
                options: {
                    production: false
                }
            }
        }
</code>

I assumed that when update is set to true, it will run bower update but I don't think it is doing so. If I run bower update in my local machine, it is updating the library version correctly to 1.11.2, but when I run it via grunt, it doesn't update the version of jquery to 1.11.2. Is there anything I can do to remedy my situation?

Thanks.

**Comment by dshrestha** [comment]
I think I figured out a solution. We were already using "grunt-contrib-clean" so I added a task to clean up the bower components folder before we run the bower install task, and that solved my issue.

**Comment by rse** [comment]
The documentation was wrong, the correct way is "command: 'update'" and not "update: true". Now fixed.
