### ISSUE TITLE
provided configuration does not work

### ISSUE THREAD

**Issue by raghavgujjar** [rse/grunt-bower-install-simple#18]
Gruntfile.js
```
require('load-grunt-tasks')(grunt);

grunt.initConfig({
       	"bower-install-simple": {
		options: {
			"dev": {
				options: {
					production: false
				}
			}
		}
	}
})

grunt.loadNpmTasks('grunt-bower-install-simple');

grunt.registerTask('bower-install',['bower-install-simple']);
```
bower.json
```
{
    "name": "projectName",
    "version": "0.0.1",
    "devDependencies": {
        "component": "^0.0.1"
    }
}
```

After running grunt bower-install, it does absolutely nothing. I see nothing in the bower components folder

**Comment by leider** [comment]
What would you expect to see there?

**Comment by raghavgujjar** [comment]
the dependencies in bower.json should be pulled into the bower_components folder.

**Comment by rse** [comment]
Your Gruntfile.js is wrong: names like "dev" are not under "options", but directly under "bower-install-simple". Move it one level up and it should work.
