### ISSUE TITLE
No "bower-install-simple" targets found

### ISSUE THREAD

**Issue by BerndErnst** [rse/grunt-bower-install-simple#20]
I put **bower-install-simple** in my **package.json** and already made a `npm install`.
My **GruntFile.js** looks like this:

    grunt.registerTask('default', ['npm-install', 'bower-install-simple', 'sass', 'uncss']);

It gives me the following error:

    >> No "bower-install-simple" targets found.
    Warning: Task "bower-install-simple" failed. Use --force to continue.
    Aborted due to warnings.

I just want to make a plain bower install. So the default parameters are fine, so I don't have to add any options for that.

Why it doesn't work?

**Comment by rse** [comment]
Grunt tasks have to be loaded first, before they can be used. You need a grunt.loadTasks() call, too.
