### ISSUE TITLE
Not respecting cwd option

### ISSUE THREAD

**Issue by badeball** [rse/grunt-bower-install-simple#5]
Hi,

I'm trying to use the `cwd` option, as my project has multiple bower.json files. However, it does not seem like this option is respected (I modified bower to output its options and I only see my own specified `directory`). It does work with the following patch.  Is this a bug?

``` patch
--- a/grunt-bower-install-simple.js 2014-07-28 13:36:50.091479137 +0200
+++ b/grunt-bower-install-simple.js 2014-07-28 13:36:47.151479103 +0200
@@ -67,7 +67,8 @@
             production:     options.production
         }, {
             interactive:    options.interactive,
-            directory:      options.directory
+            directory:      options.directory,
+            cwd:            options.cwd
         })
         .on("log", function (log) {
             renderer.log(log);
```

**Comment by newmanw** [comment]
This still seems broken.

Running grunt from project root.  bower.json is in public dir under root.

```javascript
    "bower-install-simple": {
      options: {
        cwd: 'public/'
      }
    }
```

running 'grunt bower-install-simple' produces:

Running "bower-install-simple" task

Done, without errors.
